/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.RetailRole.RetailAnalyticsRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.RetailEnterprise;
import Business.Inventory.Inventory;
import Business.Inventory.InventoryItem;
import Business.Organization.Retail.RetailInventoryOrganization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author zhifei
 */
public class InventoryAnalyticsPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private RetailInventoryOrganization organization;
    private Enterprise enterprise;
    private EcoSystem system;
    private Inventory inventory;

    /**
     * Creates new form InventoryAnalyticsPanel
     */
    public InventoryAnalyticsPanel(JPanel userProcessContainer, UserAccount account, RetailInventoryOrganization retailInventoryOrganization, Enterprise enterprise, EcoSystem system) {
        initComponents();

        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.organization = retailInventoryOrganization;
        this.enterprise = enterprise;
        this.system = system;
        this.inventory = getRetailInventory();

        populateInventoryTable();
        updateInventorySummary();
    }

    private Inventory getRetailInventory() {
        if (enterprise instanceof RetailEnterprise) {
            RetailEnterprise retailEnterprise = (RetailEnterprise) enterprise;
            return retailEnterprise.getInventory();
        }
        return enterprise.getInventory();
    }

    private void populateInventoryTable() {
        DefaultTableModel model = (DefaultTableModel) tblInventory.getModel();
        model.setRowCount(0);

        if (inventory == null) return;

        for (InventoryItem item : inventory.getProductInventory()) {
            if (item.getProduct() != null) {
                Object[] row = new Object[7];
                row[0] = item.getProduct().getProductCode();
                row[1] = item.getProduct().getProductName();
                row[2] = item.getQuantity();
                row[3] = item.getMinStockLevel();
                row[4] = String.format("$%.2f", item.getProduct().getUnitPrice());
                row[5] = String.format("$%.2f", item.getQuantity() * item.getProduct().getUnitPrice());
                row[6] = getStockStatus(item);

                model.addRow(row);
            }
        }
    }

    private String getStockStatus(InventoryItem item) {
        int available = item.getAvailableQuantity();
        int minLevel = item.getMinStockLevel();

        if (available <= 0) {
            return "Out of Stock";
        } else if (minLevel > 0 && available <= minLevel) {
            return "Critical";
        } else if (minLevel > 0 && available <= minLevel * 2) {
            return "Low Stock";
        } else {
            return "OK";
        }
    }

    private void updateInventorySummary() {
        if (inventory == null) return;

        int totalProducts = 0;
        int okItems = 0;
        int lowStockItems = 0;
        int criticalItems = 0;
        int outOfStockItems = 0;
        double totalValue = 0;

        for (InventoryItem item : inventory.getProductInventory()) {
            if (item.getProduct() != null) {
                totalProducts++;
                totalValue += item.getQuantity() * item.getProduct().getUnitPrice();

                String status = getStockStatus(item);
                if ("OK".equals(status)) {
                    okItems++;
                } else if ("Low Stock".equals(status)) {
                    lowStockItems++;
                } else if ("Critical".equals(status)) {
                    criticalItems++;
                } else if ("Out of Stock".equals(status)) {
                    outOfStockItems++;
                }
            }
        }

        txtTotalProducts.setText(String.valueOf(totalProducts));
        txtOkItems.setText(String.valueOf(okItems));
        txtLowStockItems.setText(String.valueOf(lowStockItems));
        txtCriticalItems.setText(String.valueOf(criticalItems));
        txtOutOfStockItems.setText(String.valueOf(outOfStockItems));
        txtTotalValue.setText(String.format("$%,.2f", totalValue));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnBack = new javax.swing.JButton();
        lblInventorySummary = new javax.swing.JLabel();
        lblTotalProducts = new javax.swing.JLabel();
        txtTotalProducts = new javax.swing.JTextField();
        lblOkItems = new javax.swing.JLabel();
        txtOkItems = new javax.swing.JTextField();
        lblLowStockItems = new javax.swing.JLabel();
        txtLowStockItems = new javax.swing.JTextField();
        lblCriticalItems = new javax.swing.JLabel();
        txtCriticalItems = new javax.swing.JTextField();
        lblOutOfStockItems = new javax.swing.JLabel();
        txtOutOfStockItems = new javax.swing.JTextField();
        lblTotalValue = new javax.swing.JLabel();
        txtTotalValue = new javax.swing.JTextField();
        lblInventoryDetails = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblInventory = new javax.swing.JTable();
        btnRefresh = new javax.swing.JButton();

        lblTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblTitle.setText("Inventory Analytics");

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblInventorySummary.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblInventorySummary.setText("Inventory Summary:");

        lblTotalProducts.setText("Total Products:");

        txtTotalProducts.setEditable(false);
        txtTotalProducts.setBackground(new java.awt.Color(204, 229, 255));
        txtTotalProducts.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        lblOkItems.setText("OK:");

        txtOkItems.setEditable(false);
        txtOkItems.setBackground(new java.awt.Color(204, 255, 204));
        txtOkItems.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        lblLowStockItems.setText("Low Stock:");

        txtLowStockItems.setEditable(false);
        txtLowStockItems.setBackground(new java.awt.Color(255, 255, 204));
        txtLowStockItems.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        lblCriticalItems.setText("Critical:");

        txtCriticalItems.setEditable(false);
        txtCriticalItems.setBackground(new java.awt.Color(255, 204, 153));
        txtCriticalItems.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        lblOutOfStockItems.setText("Out of Stock:");

        txtOutOfStockItems.setEditable(false);
        txtOutOfStockItems.setBackground(new java.awt.Color(255, 204, 204));
        txtOutOfStockItems.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        lblTotalValue.setText("Total Value:");

        txtTotalValue.setEditable(false);
        txtTotalValue.setBackground(new java.awt.Color(229, 204, 255));
        txtTotalValue.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        lblInventoryDetails.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblInventoryDetails.setText("Inventory Details:");

        tblInventory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product Code", "Product Name", "Quantity", "Min Level", "Unit Price", "Total Value", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblInventory);

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBack)
                            .addComponent(lblInventorySummary)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblTotalValue)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtTotalValue, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblTotalProducts)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtTotalProducts, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(20, 20, 20)
                                        .addComponent(lblOkItems)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtOkItems, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(20, 20, 20)
                                        .addComponent(lblLowStockItems)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtLowStockItems, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(20, 20, 20)
                                        .addComponent(lblCriticalItems)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtCriticalItems, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(20, 20, 20)
                                        .addComponent(lblOutOfStockItems)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtOutOfStockItems, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(lblInventoryDetails)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 38, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBack)
                .addGap(18, 18, 18)
                .addComponent(lblInventorySummary)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotalProducts)
                    .addComponent(txtTotalProducts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblOkItems)
                    .addComponent(txtOkItems, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLowStockItems)
                    .addComponent(txtLowStockItems, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCriticalItems)
                    .addComponent(txtCriticalItems, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblOutOfStockItems)
                    .addComponent(txtOutOfStockItems, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotalValue)
                    .addComponent(txtTotalValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblInventoryDetails)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRefresh)
                .addContainerGap(60, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        populateInventoryTable();
        updateInventorySummary();
    }//GEN-LAST:event_btnRefreshActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblCriticalItems;
    private javax.swing.JLabel lblInventoryDetails;
    private javax.swing.JLabel lblInventorySummary;
    private javax.swing.JLabel lblLowStockItems;
    private javax.swing.JLabel lblOkItems;
    private javax.swing.JLabel lblOutOfStockItems;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTotalProducts;
    private javax.swing.JLabel lblTotalValue;
    private javax.swing.JTable tblInventory;
    private javax.swing.JTextField txtCriticalItems;
    private javax.swing.JTextField txtLowStockItems;
    private javax.swing.JTextField txtOkItems;
    private javax.swing.JTextField txtOutOfStockItems;
    private javax.swing.JTextField txtTotalProducts;
    private javax.swing.JTextField txtTotalValue;
    // End of variables declaration//GEN-END:variables
}
