/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.RetailRole.RetailAnalyticsRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.Retail.RetailInventoryOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.RetailPurchaseOrderRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.text.SimpleDateFormat;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author zhifei
 */
public class SalesAnalyticsPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private RetailInventoryOrganization organization;
    private Enterprise enterprise;
    private EcoSystem system;

    /**
     * Creates new form SalesAnalyticsPanel
     */
    public SalesAnalyticsPanel(JPanel userProcessContainer, UserAccount account, RetailInventoryOrganization retailInventoryOrganization, Enterprise enterprise, EcoSystem system) {
        initComponents();

        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.organization = retailInventoryOrganization;
        this.enterprise = enterprise;
        this.system = system;

        populateOrdersTable();
        updateSalesSummary();
    }

    private void populateOrdersTable() {
        DefaultTableModel model = (DefaultTableModel) tblOrders.getModel();
        model.setRowCount(0);

        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm");

        for (WorkRequest request : organization.getWorkQueue().getWorkRequestList()) {
            if (request instanceof RetailPurchaseOrderRequest) {
                RetailPurchaseOrderRequest order = (RetailPurchaseOrderRequest) request;

                Object[] row = new Object[6];
                row[0] = order.getRequestId();
                row[1] = order.getProduct() != null ? order.getProduct().getProductName() : "N/A";
                row[2] = order.getQuantity();
                row[3] = order.getTotalPrice() > 0 ? String.format("$%.2f", order.getTotalPrice()) : "N/A";
                row[4] = order.getStatus();
                row[5] = order.getRequestDate() != null ? dateFormat.format(order.getRequestDate()) : "N/A";

                model.addRow(row);
            }
        }
    }

    private void updateSalesSummary() {
        int totalOrders = 0;
        int pendingOrders = 0;
        int completedOrders = 0;
        double totalValue = 0;

        for (WorkRequest request : organization.getWorkQueue().getWorkRequestList()) {
            if (request instanceof RetailPurchaseOrderRequest) {
                RetailPurchaseOrderRequest order = (RetailPurchaseOrderRequest) request;
                totalOrders++;

                String status = order.getStatus();
                if ("Pending".equalsIgnoreCase(status) || "Sent".equalsIgnoreCase(status)) {
                    pendingOrders++;
                } else if ("Delivered".equalsIgnoreCase(status) || "Completed".equalsIgnoreCase(status)) {
                    completedOrders++;
                }

                if (order.getTotalPrice() > 0) {
                    totalValue += order.getTotalPrice();
                }
            }
        }

        txtTotalOrders.setText(String.valueOf(totalOrders));
        txtPendingOrders.setText(String.valueOf(pendingOrders));
        txtCompletedOrders.setText(String.valueOf(completedOrders));
        txtTotalValue.setText(String.format("$%,.2f", totalValue));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnBack = new javax.swing.JButton();
        lblSalesSummary = new javax.swing.JLabel();
        lblTotalOrders = new javax.swing.JLabel();
        txtTotalOrders = new javax.swing.JTextField();
        lblPendingOrders = new javax.swing.JLabel();
        txtPendingOrders = new javax.swing.JTextField();
        lblCompletedOrders = new javax.swing.JLabel();
        txtCompletedOrders = new javax.swing.JTextField();
        lblTotalValue = new javax.swing.JLabel();
        txtTotalValue = new javax.swing.JTextField();
        lblOrderHistory = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblOrders = new javax.swing.JTable();
        btnRefresh = new javax.swing.JButton();

        lblTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblTitle.setText("Sales Analytics");

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblSalesSummary.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblSalesSummary.setText("Sales Summary:");

        lblTotalOrders.setText("Total Orders:");

        txtTotalOrders.setEditable(false);
        txtTotalOrders.setBackground(new java.awt.Color(204, 229, 255));
        txtTotalOrders.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        lblPendingOrders.setText("Pending:");

        txtPendingOrders.setEditable(false);
        txtPendingOrders.setBackground(new java.awt.Color(255, 255, 204));
        txtPendingOrders.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        lblCompletedOrders.setText("Completed:");

        txtCompletedOrders.setEditable(false);
        txtCompletedOrders.setBackground(new java.awt.Color(204, 255, 204));
        txtCompletedOrders.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        lblTotalValue.setText("Total Value:");

        txtTotalValue.setEditable(false);
        txtTotalValue.setBackground(new java.awt.Color(255, 204, 229));
        txtTotalValue.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        lblOrderHistory.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblOrderHistory.setText("Order History:");

        tblOrders.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Order ID", "Product", "Quantity", "Total Amount", "Status", "Order Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblOrders);

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBack)
                            .addComponent(lblSalesSummary)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(lblTotalOrders)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtTotalOrders, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(lblPendingOrders)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtPendingOrders, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(lblCompletedOrders)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtCompletedOrders, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(lblTotalValue)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtTotalValue, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblOrderHistory)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 38, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBack)
                .addGap(18, 18, 18)
                .addComponent(lblSalesSummary)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotalOrders)
                    .addComponent(txtTotalOrders, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPendingOrders)
                    .addComponent(txtPendingOrders, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCompletedOrders)
                    .addComponent(txtCompletedOrders, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTotalValue)
                    .addComponent(txtTotalValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblOrderHistory)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRefresh)
                .addContainerGap(80, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        populateOrdersTable();
        updateSalesSummary();
    }//GEN-LAST:event_btnRefreshActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblCompletedOrders;
    private javax.swing.JLabel lblOrderHistory;
    private javax.swing.JLabel lblPendingOrders;
    private javax.swing.JLabel lblSalesSummary;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTotalOrders;
    private javax.swing.JLabel lblTotalValue;
    private javax.swing.JTable tblOrders;
    private javax.swing.JTextField txtCompletedOrders;
    private javax.swing.JTextField txtPendingOrders;
    private javax.swing.JTextField txtTotalOrders;
    private javax.swing.JTextField txtTotalValue;
    // End of variables declaration//GEN-END:variables
}
