/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.ShippingRole.ShippingManagerRole;

import Business.EcoSystem;
import Business.Enterprise.ShippingEnterprise;
import Business.Organization.Shipping.ShippingOperationOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.WorkRequest;
import Business.WorkQueue.ProductShippingRequest;
import Business.WorkQueue.MaterialShippingRequest;
import Business.WorkQueue.WholesalesShippingRequest;
import java.awt.CardLayout;
import java.util.List;
import javax.swing.JPanel;
import javax.swing.JOptionPane;

/**
 *
 * @author noora.
 */
public class AssignDeliveryJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private ShippingEnterprise shippingEnterprise;
    private ShippingOperationOrganization operationOrg;
    private EcoSystem system;

    private List<WorkRequest> availableRequests;
    private List<UserAccount> staffList;

    /**
     * Creates new form AssignDeliveryJPanel
     */
    public AssignDeliveryJPanel(JPanel userProcessContainer,
            ShippingEnterprise shippingEnterprise,
            ShippingOperationOrganization operationOrg,
            EcoSystem system) {

        initComponents();

        this.userProcessContainer = userProcessContainer;
        this.shippingEnterprise = shippingEnterprise;
        this.operationOrg = operationOrg;
        this.system = system;

        loadRequests();
        loadStaff();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
// <editor-fold defaultstate="collapsed" desc="Generated Code">                         
private void initComponents() {

    btnBack = new javax.swing.JButton();
    lblTitle = new javax.swing.JLabel();
    lblSelectRequest = new javax.swing.JLabel();
    cmbRequests = new javax.swing.JComboBox<>();
    lblSelectStaff = new javax.swing.JLabel();
    cmbStaff = new javax.swing.JComboBox<>();
    btnAssign = new javax.swing.JButton();
    jScrollPane2 = new javax.swing.JScrollPane();
    txtRequestDetails = new javax.swing.JTextArea();

    setBackground(new java.awt.Color(0, 153, 255));

    btnBack.setText("<< Back");
    btnBack.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnBackActionPerformed(evt);
        }
    });

    lblTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); 
    lblTitle.setText("Assign Delivery Staff");

    lblSelectRequest.setText("Select Request:");

    cmbRequests.setModel(new javax.swing.DefaultComboBoxModel<>());
    cmbRequests.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            cmbRequestsActionPerformed(evt);
        }
    });

    lblSelectStaff.setText("Assign Delivery Staff:");

    cmbStaff.setModel(new javax.swing.DefaultComboBoxModel<>());

    btnAssign.setText("Assign");
    btnAssign.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnAssignActionPerformed(evt);
        }
    });

    txtRequestDetails.setEditable(false);
    txtRequestDetails.setColumns(20);
    txtRequestDetails.setLineWrap(true);
    txtRequestDetails.setRows(5);
    txtRequestDetails.setWrapStyleWord(true);
    jScrollPane2.setViewportView(txtRequestDetails);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addGap(20, 20, 20)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(btnBack)
                .addComponent(lblTitle)
                .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblSelectRequest)
                        .addComponent(lblSelectStaff))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(cmbRequests, 0, 250, Short.MAX_VALUE)
                        .addComponent(cmbStaff, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAssign)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap(20, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addGap(20, 20, 20)
            .addComponent(btnBack)
            .addGap(18, 18, 18)
            .addComponent(lblTitle)
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lblSelectRequest)
                .addComponent(cmbRequests, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lblSelectStaff)
                .addComponent(cmbStaff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addComponent(btnAssign)
            .addGap(18, 18, 18)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(20, Short.MAX_VALUE))
    );
}                        
// </editor-fold> 


    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void cmbRequestsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbRequestsActionPerformed
        // TODO add your handling code here:
        showSelectedRequestDetails();
    }//GEN-LAST:event_cmbRequestsActionPerformed

    private void btnAssignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignActionPerformed
        // TODO add your handling code here:
        if (availableRequests == null || availableRequests.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No request selected.");
            return;
        }
        int reqIdx = cmbRequests.getSelectedIndex();
        int staffIdx = cmbStaff.getSelectedIndex();

        if (reqIdx < 0 || reqIdx >= availableRequests.size()) {
            JOptionPane.showMessageDialog(this, "Please select a request.");
            return;
        }
        if (staffList == null || staffList.isEmpty() || staffIdx < 0 || staffIdx >= staffList.size()) {
            JOptionPane.showMessageDialog(this, "Please select a delivery staff.");
            return;
        }

        WorkRequest wr = availableRequests.get(reqIdx);
        UserAccount staff = staffList.get(staffIdx);

        wr.setReceiver(staff);
        wr.setStatus(WorkRequest.STATUS_IN_PROGRESS);

        if (!staff.getWorkQueue().getWorkRequestList().contains(wr)) {
            staff.getWorkQueue().addWorkRequest(wr);
        }

        JOptionPane.showMessageDialog(this,
                "Request #" + wr.getRequestId() + " assigned to " + staff.getUsername() + ".");

        showSelectedRequestDetails();
    }//GEN-LAST:event_btnAssignActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssign;
    private javax.swing.JButton btnBack;
    private javax.swing.JComboBox<String> cmbRequests;
    private javax.swing.JComboBox<String> cmbStaff;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblSelectRequest;
    private javax.swing.JLabel lblSelectStaff;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextArea txtRequestDetails;
    // End of variables declaration//GEN-END:variables

    private void loadRequests() {
        cmbRequests.removeAllItems();

        availableRequests = new java.util.ArrayList<>();

        for (WorkRequest wr : operationOrg.getWorkQueue().getWorkRequestList()) {
            if (wr instanceof ProductShippingRequest
                    || wr instanceof MaterialShippingRequest
                    || wr instanceof WholesalesShippingRequest) {

                if (WorkRequest.STATUS_DELIVERED.equals(wr.getStatus())
                        || WorkRequest.STATUS_CANCELLED.equals(wr.getStatus())) {
                    continue;
                }

                availableRequests.add(wr);
            }
        }

        if (availableRequests.isEmpty()) {
            cmbRequests.addItem("No active shipping requests");
            cmbRequests.setEnabled(false);
            btnAssign.setEnabled(false);
            txtRequestDetails.setText("");
            return;
        }

        for (WorkRequest wr : availableRequests) {
            String label = buildRequestLabel(wr);
            cmbRequests.addItem(label);
        }

        cmbRequests.setSelectedIndex(0);
        cmbRequests.setEnabled(true);
        btnAssign.setEnabled(true);

        showSelectedRequestDetails();
    }

    private String buildRequestLabel(WorkRequest wr) {
        String base = "Request #" + wr.getRequestId() + " - ";

        if (wr instanceof ProductShippingRequest) {
            ProductShippingRequest psr = (ProductShippingRequest) wr;
            base += "Product: " + psr.getProductName()
                    + " → " + psr.getDestinationStoreName();
        } else if (wr instanceof MaterialShippingRequest) {
            MaterialShippingRequest msr = (MaterialShippingRequest) wr;
            base += "Material: " + msr.getMaterialName()
                    + " → " + (msr.getTargetEnterprise() == null
                    ? "-"
                    : msr.getTargetEnterprise().getName());
        } else if (wr instanceof WholesalesShippingRequest) {
            WholesalesShippingRequest wsr = (WholesalesShippingRequest) wr;
            base += "Wholesale: " + wsr.getProductName()
                    + " → " + wsr.getDestinationAddress();
        } else {
            base += wr.getStatus();
        }

        return base;
    }

    private void showSelectedRequestDetails() {
        int idx = cmbRequests.getSelectedIndex();
        if (availableRequests == null || availableRequests.isEmpty() || idx < 0 || idx >= availableRequests.size()) {
            txtRequestDetails.setText("");
            return;
        }

        WorkRequest wr = availableRequests.get(idx);
        StringBuilder sb = new StringBuilder();

        sb.append("Request ID: ").append(wr.getRequestId()).append("\n");
        sb.append("Status: ").append(wr.getStatus()).append("\n");
        sb.append("Priority: ").append(wr.getPriorityLabel()).append("\n");
        sb.append("Created: ").append(wr.getRequestDate()).append("\n");
        sb.append("Last Updated: ").append(wr.getLastUpdated()).append("\n\n");

        if (wr instanceof ProductShippingRequest) {
            ProductShippingRequest psr = (ProductShippingRequest) wr;
            sb.append("Type: Product Shipping\n");
            sb.append("Product: ").append(psr.getProductName()).append("\n");
            sb.append("Quantity: ").append(psr.getQuantity())
                    .append(" ").append(psr.getUnit()).append("\n");
            sb.append("From: ")
                    .append(psr.getSourceEnterprise() == null ? "-" : psr.getSourceEnterprise().getName())
                    .append("\n");
            sb.append("To (Store): ").append(psr.getDestinationStoreName()).append("\n");

        } else if (wr instanceof MaterialShippingRequest) {
            MaterialShippingRequest msr = (MaterialShippingRequest) wr;
            sb.append("Type: Material Shipping\n");
            sb.append("Material: ").append(msr.getMaterialName()).append("\n");
            sb.append("Quantity: ").append(msr.getQuantity())
                    .append(" ").append(msr.getUnit()).append("\n");
            sb.append("From: ")
                    .append(msr.getSourceEnterprise() == null ? "-" : msr.getSourceEnterprise().getName())
                    .append("\n");
            sb.append("To: ")
                    .append(msr.getTargetEnterprise() == null ? "-" : msr.getTargetEnterprise().getName())
                    .append("\n");

        } else if (wr instanceof WholesalesShippingRequest) {
            WholesalesShippingRequest wsr = (WholesalesShippingRequest) wr;
            sb.append("Type: Wholesale Shipping\n");
            sb.append("Product: ").append(wsr.getProductName()).append("\n");
            sb.append("Quantity: ").append(wsr.getQuantity())
                    .append(" ").append(wsr.getUnit()).append("\n");
            sb.append("Origin: ").append(wsr.getOriginAddress()).append("\n");
            sb.append("Destination: ").append(wsr.getDestinationAddress()).append("\n");
            sb.append("Shipping Status: ").append(wsr.getShippingStatus()).append("\n");
        }

        txtRequestDetails.setText(sb.toString());
    }

    private void loadStaff() {
        cmbStaff.removeAllItems();

        staffList = operationOrg.getUserAccountDirectory().getUserAccountList();

        if (staffList.isEmpty()) {
            cmbStaff.addItem("No staff available");
            cmbStaff.setEnabled(false);
            btnAssign.setEnabled(false);
            return;
        }

        for (UserAccount ua : staffList) {
            cmbStaff.addItem(ua.getUsername());
        }
    }

}
