/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.ShippingRole.ShippingManagerRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.ShippingEnterprise;
import Business.Organization.Organization;
import Business.Organization.Shipping.ShippingManagementOrganization;
import Business.Organization.Shipping.ShippingOperationOrganization;
import Business.UserAccount.UserAccount;
import javax.swing.JPanel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Business.WorkQueue.WorkRequest;
import Business.WorkQueue.ProductShippingRequest;
import Business.WorkQueue.MaterialShippingRequest;
import Business.WorkQueue.WholesalesShippingRequest;
import java.awt.CardLayout;

/**
 *
 * @author chris
 */
public class ShippingManagerRoleWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private ShippingManagementOrganization managementOrg;
    private ShippingEnterprise shippingEnterprise;
    private EcoSystem system;

    /**
     * Creates new form DeliveryStaffWorkAreaJPanel
     */
    public ShippingManagerRoleWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, ShippingManagementOrganization par, Enterprise enterprise, EcoSystem system) {
        initComponents();

        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.managementOrg = par;
        this.shippingEnterprise = (ShippingEnterprise) enterprise;
        this.system = system;

        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        lblTitle = new javax.swing.JLabel();
        jScrollPaneRequests = new javax.swing.JScrollPane();
        tblRequests = new javax.swing.JTable();
        panelButtons = new javax.swing.JPanel();
        btnRefresh = new javax.swing.JButton();
        btnSendToOperation = new javax.swing.JButton();
        btnOpenAssignUI = new javax.swing.JButton();

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        setBackground(new java.awt.Color(0, 153, 255));

        lblTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblTitle.setText("Manage Shipping Requests:");

        tblRequests.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Request", "Type", "Item", "Quantity", "From", "Destination", "Status", "Assigned to "
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPaneRequests.setViewportView(tblRequests);

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        btnSendToOperation.setText("Send to Operations");
        btnSendToOperation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendToOperationActionPerformed(evt);
            }
        });

        btnOpenAssignUI.setText("Assign Delivery Staff");
        btnOpenAssignUI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenAssignUIActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelButtonsLayout = new javax.swing.GroupLayout(panelButtons);
        panelButtons.setLayout(panelButtonsLayout);
        panelButtonsLayout.setHorizontalGroup(
            panelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnRefresh)
                .addGap(18, 18, 18)
                .addComponent(btnOpenAssignUI)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSendToOperation)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelButtonsLayout.setVerticalGroup(
            panelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRefresh)
                    .addComponent(btnSendToOperation)
                    .addComponent(btnOpenAssignUI))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setText("Open Assign Staff UI");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPaneRequests, javax.swing.GroupLayout.DEFAULT_SIZE, 916, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(270, 270, 270)
                        .addComponent(lblTitle)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(204, 204, 204)
                .addComponent(panelButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblTitle)
                .addGap(18, 18, 18)
                .addComponent(jScrollPaneRequests, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        populateTable();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnSendToOperationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendToOperationActionPerformed
        // TODO add your handling code here:
        WorkRequest wr = getSelectedRequest();
        if (wr == null) {
            return;
        }

        ShippingOperationOrganization opOrg = null;
        for (Organization org : shippingEnterprise.getOrganizationDirectory().getOrganizationList()) {
            if (org instanceof ShippingOperationOrganization) {
                opOrg = (ShippingOperationOrganization) org;
                break;
            }
        }

        if (opOrg == null) {
            JOptionPane.showMessageDialog(this,
                    "No Shipping Operation Organization found in this ShippingEnterprise.");
            return;
        }

        wr.setTargetOrganization(opOrg);
        if (!opOrg.getWorkQueue().getWorkRequestList().contains(wr)) {
            opOrg.getWorkQueue().addWorkRequest(wr);
        }

        JOptionPane.showMessageDialog(this,
                "Request sent to Shipping Operation for delivery staff.");
    }//GEN-LAST:event_btnSendToOperationActionPerformed

    private void btnOpenAssignUIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenAssignUIActionPerformed
        // TODO add your handling code here:
        ShippingOperationOrganization opOrg = null;
        for (Organization org : shippingEnterprise.getOrganizationDirectory().getOrganizationList()) {
            if (org instanceof ShippingOperationOrganization) {
                opOrg = (ShippingOperationOrganization) org;
                break;
            }
        }

        if (opOrg == null) {
            JOptionPane.showMessageDialog(this,
                    "No Shipping Operation Organization found in this ShippingEnterprise.");
            return;
        }

        AssignDeliveryJPanel panel = new AssignDeliveryJPanel(
                userProcessContainer, shippingEnterprise, opOrg, system);
        userProcessContainer.add("AssignDeliveryStaffJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnOpenAssignUIActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOpenAssignUI;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSendToOperation;
    private javax.swing.JButton jButton1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPaneRequests;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel panelButtons;
    private javax.swing.JTable tblRequests;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) tblRequests.getModel();
        model.setRowCount(0);

        for (WorkRequest wr : managementOrg.getWorkQueue().getWorkRequestList()) {
            if (wr instanceof ProductShippingRequest
                    || wr instanceof MaterialShippingRequest
                    || wr instanceof WholesalesShippingRequest) {

                Object[] row = new Object[8];
                row[0] = wr;

                if (wr instanceof ProductShippingRequest) {
                    ProductShippingRequest psr = (ProductShippingRequest) wr;
                    row[1] = "Product";
                    row[2] = psr.getProductName();
                    row[3] = psr.getQuantity() + " " + psr.getUnit();
                    row[4] = psr.getSourceEnterprise() == null
                            ? "-"
                            : psr.getSourceEnterprise().getName();
                    row[5] = psr.getDestinationStoreName();
                    row[6] = psr.getStatus();
                    row[7] = psr.getReceiver() == null
                            ? "Unassigned"
                            : psr.getReceiver().getUsername();

                } else if (wr instanceof MaterialShippingRequest) {
                    MaterialShippingRequest msr = (MaterialShippingRequest) wr;
                    row[1] = "Material";
                    row[2] = msr.getMaterialName();
                    row[3] = msr.getQuantity() + " " + msr.getUnit();
                    row[4] = msr.getSourceEnterprise() == null
                            ? "-"
                            : msr.getSourceEnterprise().getName();
                    row[5] = msr.getTargetEnterprise() == null
                            ? "-"
                            : msr.getTargetEnterprise().getName();
                    row[6] = msr.getStatus();
                    row[7] = msr.getReceiver() == null
                            ? "Unassigned"
                            : msr.getReceiver().getUsername();

                } else if (wr instanceof WholesalesShippingRequest) {
                    WholesalesShippingRequest wsr = (WholesalesShippingRequest) wr;
                    row[1] = "Wholesale";
                    row[2] = wsr.getProductName();
                    row[3] = wsr.getQuantity() + " " + wsr.getUnit();
                    row[4] = wsr.getOriginAddress();
                    row[5] = wsr.getDestinationAddress();
                    row[6] = wsr.getShippingStatus();
                    row[7] = wsr.getReceiver() == null
                            ? "Unassigned"
                            : wsr.getReceiver().getUsername();
                }

                model.addRow(row);
            }
        }
    }

    private WorkRequest getSelectedRequest() {
        int selectedRow = tblRequests.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a row.");
            return null;
        }
        return (WorkRequest) tblRequests.getValueAt(selectedRow, 0);
    }

}
