/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.RetailRole.StoreManagerRole;

import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Organization.Retail.StoreManagementOrganization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author zhifei
 */
public class ManageStoreStaffPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private StoreManagementOrganization organization;
    private Enterprise enterprise;
    private EcoSystem system;

    /**
     * Creates new form ManageStoreStaffPanel
     */
    public ManageStoreStaffPanel(JPanel userProcessContainer, UserAccount account, StoreManagementOrganization storeManagementOrganization, Enterprise enterprise, EcoSystem system) {
        initComponents();

        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.organization = storeManagementOrganization;
        this.enterprise = enterprise;
        this.system = system;

        populateStaffTable();
        updateSummary();
    }

    private void populateStaffTable() {
        DefaultTableModel model = (DefaultTableModel) tblStaff.getModel();
        model.setRowCount(0);

        for (UserAccount account : organization.getUserAccountDirectory().getUserAccountList()) {
            Employee emp = account.getEmployee();
            if (emp != null) {
                Object[] row = new Object[5];
                row[0] = emp.getId();
                row[1] = emp.getName();
                row[2] = account.getRole() != null ? account.getRole().toString() : "N/A";
                row[3] = emp.getEmail() != null ? emp.getEmail() : "N/A";
                row[4] = emp.getPhone() != null ? emp.getPhone() : "N/A";
                model.addRow(row);
            }
        }
    }

    private void updateSummary() {
        int totalStaff = organization.getUserAccountDirectory().getUserAccountList().size();
        txtTotalStaff.setText(String.valueOf(totalStaff));

        int managers = 0;
        int clerks = 0;
        int analysts = 0;

        for (UserAccount account : organization.getUserAccountDirectory().getUserAccountList()) {
            if (account.getRole() != null) {
                String roleName = account.getRole().toString().toLowerCase();
                if (roleName.contains("manager")) {
                    managers++;
                } else if (roleName.contains("clerk")) {
                    clerks++;
                } else if (roleName.contains("analytics") || roleName.contains("analyst")) {
                    analysts++;
                }
            }
        }

        txtManagers.setText(String.valueOf(managers));
        txtClerks.setText(String.valueOf(clerks));
    }

    private UserAccount getSelectedStaff() {
        int selectedRow = tblStaff.getSelectedRow();
        if (selectedRow < 0) {
            return null;
        }

        int empId = (Integer) tblStaff.getValueAt(selectedRow, 0);
        for (UserAccount account : organization.getUserAccountDirectory().getUserAccountList()) {
            if (account.getEmployee() != null && account.getEmployee().getId() == empId) {
                return account;
            }
        }
        return null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnBack = new javax.swing.JButton();
        lblStaffSummary = new javax.swing.JLabel();
        lblTotalStaff = new javax.swing.JLabel();
        txtTotalStaff = new javax.swing.JTextField();
        lblManagers = new javax.swing.JLabel();
        txtManagers = new javax.swing.JTextField();
        lblClerks = new javax.swing.JLabel();
        txtClerks = new javax.swing.JTextField();
        lblStaffList = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStaff = new javax.swing.JTable();
        lblActions = new javax.swing.JLabel();
        btnViewDetails = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();

        lblTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblTitle.setText("Manage Store Staff");

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblStaffSummary.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblStaffSummary.setText("Staff Summary:");

        lblTotalStaff.setText("Total Staff:");

        txtTotalStaff.setEditable(false);
        txtTotalStaff.setBackground(new java.awt.Color(204, 229, 255));
        txtTotalStaff.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        lblManagers.setText("Managers:");

        txtManagers.setEditable(false);
        txtManagers.setBackground(new java.awt.Color(204, 255, 204));
        txtManagers.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        lblClerks.setText("Clerks:");

        txtClerks.setEditable(false);
        txtClerks.setBackground(new java.awt.Color(255, 255, 204));
        txtClerks.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        lblStaffList.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblStaffList.setText("Staff List:");

        tblStaff.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Employee ID", "Name", "Role", "Email", "Phone"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblStaff);

        lblActions.setText("Actions:");

        btnViewDetails.setText("View Details");
        btnViewDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDetailsActionPerformed(evt);
            }
        });

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBack)
                            .addComponent(lblStaffSummary)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(lblTotalStaff)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtTotalStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(lblManagers)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtManagers, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(lblClerks)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtClerks, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblStaffList)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(lblActions)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnViewDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 88, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBack)
                .addGap(18, 18, 18)
                .addComponent(lblStaffSummary)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotalStaff)
                    .addComponent(txtTotalStaff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblManagers)
                    .addComponent(txtManagers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblClerks)
                    .addComponent(txtClerks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblStaffList)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblActions)
                    .addComponent(btnViewDetails)
                    .addComponent(btnRefresh))
                .addContainerGap(100, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnViewDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDetailsActionPerformed
        UserAccount selectedAccount = getSelectedStaff();
        if (selectedAccount == null) {
            JOptionPane.showMessageDialog(this,
                    "Please select a staff member from the table.",
                    "No Selection", JOptionPane.WARNING_MESSAGE);
            return;
        }

        Employee emp = selectedAccount.getEmployee();
        StringBuilder details = new StringBuilder();
        details.append("Staff Details\n");
        details.append("================\n\n");
        details.append("Employee ID: ").append(emp.getId()).append("\n");
        details.append("Name: ").append(emp.getName()).append("\n");
        details.append("Email: ").append(emp.getEmail() != null ? emp.getEmail() : "N/A").append("\n");
        details.append("Phone: ").append(emp.getPhone() != null ? emp.getPhone() : "N/A").append("\n\n");
        details.append("Account Information\n");
        details.append("================\n\n");
        details.append("Username: ").append(selectedAccount.getUsername()).append("\n");
        details.append("Role: ").append(selectedAccount.getRole() != null ? selectedAccount.getRole().toString() : "N/A").append("\n");

        JOptionPane.showMessageDialog(this, details.toString(), "Staff Details", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnViewDetailsActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        populateStaffTable();
        updateSummary();
        JOptionPane.showMessageDialog(this, "Staff list refreshed.", "Refresh", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnRefreshActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnViewDetails;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblActions;
    private javax.swing.JLabel lblClerks;
    private javax.swing.JLabel lblManagers;
    private javax.swing.JLabel lblStaffList;
    private javax.swing.JLabel lblStaffSummary;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTotalStaff;
    private javax.swing.JTable tblStaff;
    private javax.swing.JTextField txtClerks;
    private javax.swing.JTextField txtManagers;
    private javax.swing.JTextField txtTotalStaff;
    // End of variables declaration//GEN-END:variables
}
