/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.ManufacturerRole.InventoryManagerRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.Manufacturer.InventoryOrganization;
import Business.Organization.Organization;
import Business.WorkQueue.RawMaterialRestockRequest;
import Business.WorkQueue.WorkRequest;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author zhaojinkun
 */
public class ManageRestockRequestJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageRestockRequestJPanel
     */
    JPanel userProcessContainer;
    Organization rmProcurementOrg;
    Enterprise enterprise;
    EcoSystem system;
    public ManageRestockRequestJPanel(JPanel userProcessContainer, Organization rmProcurementOrg, Enterprise enterprise, EcoSystem system) {
        this.userProcessContainer = userProcessContainer;
        this.rmProcurementOrg = rmProcurementOrg;
        this.enterprise = enterprise;
        this.system = system;
        initComponents();
        populateTable();
    }
    
    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) tbProduct.getModel();
        model.setRowCount(0);
        for (WorkRequest req : rmProcurementOrg.getWorkQueue().getWorkRequestList()) {
            if (req instanceof RawMaterialRestockRequest) { 
                RawMaterialRestockRequest rmReq = (RawMaterialRestockRequest) req;
                Object[] row = new Object[7];
                row[0] = rmReq.getRequestId();
                row[1] = rmReq.getMaterial().getMaterialName();
                row[2] = rmReq.getQuantity();
                row[3] = rmReq.getMaterial().getUnit();
                row[4] = rmReq.getQuantity() * rmReq.getMaterial().getUnitPrice();  // total
                row[5] = rmReq.getStatus();
                row[6] = rmReq.getRequestDate();
                model.addRow(row);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        btnDeleteRequest = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbProduct = new javax.swing.JTable();
        btnEditQuantity = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel1.setText("Restock Request Management");

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnDeleteRequest.setText("Delete");
        btnDeleteRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteRequestActionPerformed(evt);
            }
        });

        tbProduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Request ID", "Material", "Qty", "Unit", "Total", "Status", "Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbProduct);

        btnEditQuantity.setText("Edit Quantity");
        btnEditQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditQuantityActionPerformed(evt);
            }
        });

        jLabel2.setText("Requests Table ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBack))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 784, Short.MAX_VALUE)
                    .addComponent(jSeparator3)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnDeleteRequest)
                                .addGap(18, 18, 18)
                                .addComponent(btnEditQuantity)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBack))
                .addGap(17, 17, 17)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDeleteRequest)
                    .addComponent(btnEditQuantity))
                .addContainerGap(15, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        ((java.awt.CardLayout) userProcessContainer.getLayout()).next(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnDeleteRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteRequestActionPerformed
        // TODO add your handling code here:
        int selectedRow = tbProduct.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a request to delete");
            return;
        }

        DefaultTableModel model = (DefaultTableModel) tbProduct.getModel();
        int requestId = (int) model.getValueAt(selectedRow, 0); // 假设第0列是 requestId

        WorkRequest toRemove = null;
        for (WorkRequest req : rmProcurementOrg.getWorkQueue().getWorkRequestList()) {
            if (req instanceof RawMaterialRestockRequest) {
                RawMaterialRestockRequest rmReq = (RawMaterialRestockRequest) req;
                if (rmReq.getRequestId() == requestId) {
                    toRemove = rmReq;
                    break;
                }
            }
        }
        if (toRemove != null) {
            rmProcurementOrg.getWorkQueue().getWorkRequestList().remove(toRemove);
            JOptionPane.showMessageDialog(this, "Request deleted successfully!");
            populateTable(); 
        } else {
            JOptionPane.showMessageDialog(this, "Request not found!");
        }
        
    }//GEN-LAST:event_btnDeleteRequestActionPerformed

    private void btnEditQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditQuantityActionPerformed
        // TODO add your handling code here:
        int selectedRow = tbProduct.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a request to edit");
            return;
        }

        DefaultTableModel model = (DefaultTableModel) tbProduct.getModel();
        int requestId = (int) model.getValueAt(selectedRow, 0); 

        RawMaterialRestockRequest toEdit = null;
        for (WorkRequest req : rmProcurementOrg.getWorkQueue().getWorkRequestList()) {
            if (req instanceof RawMaterialRestockRequest) {
                RawMaterialRestockRequest rmReq = (RawMaterialRestockRequest) req;
                if (rmReq.getRequestId() == requestId) {
                    toEdit = rmReq;
                    break;
                }
            }
        }

        if (toEdit != null) {
            String input = JOptionPane.showInputDialog(this, "Enter new quantity:", toEdit.getQuantity());
            if (input != null && !input.isEmpty()) {
                try {
                    int newQuantity = Integer.parseInt(input);
                    if (newQuantity <= 0) {
                        JOptionPane.showMessageDialog(this, "Quantity must be positive");
                        return;
                    }
                    toEdit.setQuantity(newQuantity);
                    JOptionPane.showMessageDialog(this, "Quantity updated successfully!");
                    populateTable(); 
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(this, "Invalid number format");
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Request not found!");
        }
    }//GEN-LAST:event_btnEditQuantityActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDeleteRequest;
    private javax.swing.JButton btnEditQuantity;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable tbProduct;
    // End of variables declaration//GEN-END:variables
}
