/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.ManufacturerRole.InventoryManagerRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.ManufacturerEnterprise;
import Business.Inventory.InventoryItem;
import Business.Material.Material;
import Business.Material.MaterialCatalog;
import Business.Organization.Manufacturer.InventoryOrganization;
import Business.Organization.Organization;
import Business.Product.Product;
import Business.Product.ProductCatalog;
import Business.WorkQueue.RawMaterialRestockRequest;
import java.util.HashSet;
import java.util.Set;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author zhaojinkun
 */
public class ProductInventoryJPanel extends javax.swing.JPanel {

    /**
     * Creates new form RawMaterialInventoryJPanel
     */
    
    JPanel userProcessContainer;
    InventoryOrganization inventoryOrganization;
    Enterprise enterprise;
    EcoSystem system;
    
    public ProductInventoryJPanel(JPanel userProcessContainer, InventoryOrganization inventoryOrganization, Enterprise enterprise, EcoSystem system) {
        this.userProcessContainer = userProcessContainer;
        this.inventoryOrganization = inventoryOrganization;
        this.enterprise = enterprise;
        initComponents();
        populateComboBox();
        populateTable("All");
    }
    
    private void populateComboBox(){
        // Order Status
        cbCategory.removeAllItems();
        cbCategory.addItem("All");
        ManufacturerEnterprise mfg = (ManufacturerEnterprise) enterprise;
        ProductCatalog productCatalog = mfg.getProductCatalog();

        Set<String> categorySet = new HashSet<>();

        for (Product p : productCatalog.getActiveProducts()) {
            if (p.getCategory() != null && !p.getCategory().isEmpty()) {
                categorySet.add(p.getCategory());
            }
        }

        for (String category : categorySet) {
            cbCategory.addItem(category);
        }
    }
    
    
    
    private void populateTable(String selectedCategory) {
        if (selectedCategory == null) {
            return; 
        }

        DefaultTableModel model = (DefaultTableModel) tbProduct.getModel();
        model.setRowCount(0);

        boolean showLowStockOnly = rbtnLowerStockOnly.isSelected();  

        for (InventoryItem item : enterprise.getInventory().getProductInventory()) {
            String itemCategory = item.getProduct().getCategory();


            if (!selectedCategory.equals("All")
                    && !itemCategory.equalsIgnoreCase(selectedCategory)) {
                continue;
            }

            if (showLowStockOnly && !item.isLowStock()) {
                continue; 
            }

            Object[] row = new Object[]{
                item.getProduct().getProductId(),
                item.getProduct().getProductCode(),
                item.getProduct().getProductName(),
                item.getProduct().getCategory(),
                item.getQuantity(),
                item.getProduct().getUnit(),
                item.getLocation(),
                item.isLowStock() ? "Low Stock" : "Normal"
            };

            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fieldProductCode = new javax.swing.JTextField();
        btnSearchCode = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbProduct = new javax.swing.JTable();
        btnEditQuantity = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        cbCategory = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        btnViewProductDetail = new javax.swing.JButton();
        rbtnLowerStockOnly = new javax.swing.JRadioButton();
        btnBack = new javax.swing.JButton();
        btnSearchName = new javax.swing.JButton();
        fieldProductName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        jTextField2.setText("jTextField2");

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel1.setText("Product Inventory Management");

        jLabel2.setText("Product Code:");

        btnSearchCode.setText("Search");
        btnSearchCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchCodeActionPerformed(evt);
            }
        });

        tbProduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product ID", "Product Code ", "Product Name", "Category", "Qty", "Unit", "Location", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbProduct);

        btnEditQuantity.setText("Edit Quantity");
        btnEditQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditQuantityActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 2, 14)); // NOI18N
        jLabel3.setText("Filters:");

        cbCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCategoryActionPerformed(evt);
            }
        });

        jLabel4.setText("Category:");

        btnViewProductDetail.setText("View Product Details");
        btnViewProductDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewProductDetailActionPerformed(evt);
            }
        });

        rbtnLowerStockOnly.setText("Low Stock Only");
        rbtnLowerStockOnly.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnLowerStockOnlyActionPerformed(evt);
            }
        });

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnSearchName.setText("Search");
        btnSearchName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchNameActionPerformed(evt);
            }
        });

        jLabel5.setText("Product Name:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2)
                    .addComponent(jSeparator1)
                    .addComponent(jSeparator3)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnViewProductDetail)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnEditQuantity))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(fieldProductCode, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(cbCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(btnSearchCode, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(rbtnLowerStockOnly)))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(fieldProductName, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnSearchName, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(31, 31, 31)))))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 784, Short.MAX_VALUE))
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBack))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(cbCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rbtnLowerStockOnly))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(fieldProductCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchCode))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(fieldProductName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchName))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnViewProductDetail)
                    .addComponent(btnEditQuantity))
                .addContainerGap(13, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditQuantityActionPerformed
        // TODO add your handling code here:
        int selectedRow = tbProduct.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a material to edit.", "No Selection", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String productCode = (String) tbProduct.getValueAt(selectedRow, 1);

        InventoryItem item = enterprise.getInventory().findByProductCode(productCode);

        String newQtyStr = JOptionPane.showInputDialog(this, "Enter new quantity for " + item.getProduct().getProductName()+ ":", item.getQuantity());
        if (newQtyStr == null) {
            return;
        }

        try {
            int newQty = Integer.parseInt(newQtyStr);
            if (newQty < 0) {
                JOptionPane.showMessageDialog(this, "Quantity cannot be negative.", "Invalid Input", JOptionPane.WARNING_MESSAGE);
                return;
            }
            
            if (newQty > item.getMaxStockLevel()) {
                JOptionPane.showMessageDialog(this, 
                    "Quantity cannot exceed max stock level (" + item.getMaxStockLevel() + ").", 
                    "Invalid Input", 
                    JOptionPane.WARNING_MESSAGE);
                return;
            }

            item.setQuantity(newQty);

            String selectedCategory = (String) cbCategory.getSelectedItem();
            populateTable(selectedCategory);

            JOptionPane.showMessageDialog(this, "Quantity updated successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Please enter a valid integer.", "Invalid Input", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnEditQuantityActionPerformed

    private void btnViewProductDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewProductDetailActionPerformed
        // TODO add your handling code here:
        int selectedRow = tbProduct.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a product first.", "No Selection", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String productCode = (String) tbProduct.getValueAt(selectedRow, 1);
        InventoryItem item = enterprise.getInventory().findByProductCode(productCode);

        if (item != null) {
            Product product = item.getProduct();
            String details = "Product ID: " + product.getProductId()+ "\n"
                           + "Product Code: " + product.getProductCode()+ "\n"
                           + "Product Name: " + product.getProductName()+ "\n"
                           + "Category: " + product.getCategory()+ "\n"
                           + "Unit Price: " + product.getUnitPrice()+ "\n"
                           + "Description: " + product.getDescription() + "\n"
                           + "Quantity: " + item.getQuantity() + "\n"
                           + "Unit: " + product.getUnit() + "\n"
                           + "Location: " + item.getLocation() + "\n"
                           + "Min Stock Level: " + item.getMinStockLevel() + "\n"
                           + "Max Stock Level: " + item.getMaxStockLevel() + "\n"
                           + "Status: " + (item.isLowStock() ? "Low Stock" : "Normal");

            JOptionPane.showMessageDialog(this, details, "Product Details", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Product not found in inventory.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnViewProductDetailActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
         userProcessContainer.remove(this);
        ((java.awt.CardLayout) userProcessContainer.getLayout()).next(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void cbCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCategoryActionPerformed
        // TODO add your handling code here:
        String selectedCategory = (String) cbCategory.getSelectedItem();
        populateTable(selectedCategory);
    }//GEN-LAST:event_cbCategoryActionPerformed

    private void rbtnLowerStockOnlyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnLowerStockOnlyActionPerformed
        // TODO add your handling code here:
        String selectedCategory = (String) cbCategory.getSelectedItem();
        populateTable(selectedCategory);
        
    }//GEN-LAST:event_rbtnLowerStockOnlyActionPerformed

    private void btnSearchCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchCodeActionPerformed
        // TODO add your handling code here:
        String productCode = fieldProductCode.getText().trim();
    
        DefaultTableModel model = (DefaultTableModel) tbProduct.getModel();
        model.setRowCount(0); 

        if (productCode.isEmpty()) {
            populateTable("All"); 
            return;
        }

        InventoryItem item = enterprise.getInventory().findByProductCode(productCode);

        if (item != null) {
            if (rbtnLowerStockOnly.isSelected() && !item.isLowStock()) {
                return; 
            }

            Object[] row = new Object[]{
                item.getProduct().getProductId(),
                item.getProduct().getProductCode(),
                item.getProduct().getProductName(),
                item.getProduct().getCategory(),
                item.getQuantity(),
                item.getProduct().getUnit(),
                item.getLocation(),
                item.isLowStock() ? "Low Stock" : "Normal"
            };
            model.addRow(row);
        } else {
            JOptionPane.showMessageDialog(this, "No Product found with code: " + productCode);
        }

    }//GEN-LAST:event_btnSearchCodeActionPerformed

    private void btnSearchNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchNameActionPerformed
        // TODO add your handling code here:
         String searchName = fieldProductName.getText().trim().toLowerCase();
    
        DefaultTableModel model = (DefaultTableModel) tbProduct.getModel();
        model.setRowCount(0);

        if (searchName.isEmpty()) {
            populateTable("All");
            return;
        }

        for (InventoryItem item : enterprise.getInventory().getProductInventory()) {
            String productName = item.getProduct().getProductName().toLowerCase();

            if (!productName.contains(searchName)) {
                continue; 
            }

            if (rbtnLowerStockOnly.isSelected() && !item.isLowStock()) {
                continue;
            }

            Object[] row = new Object[]{
                item.getProduct().getProductId(),
                item.getProduct().getProductCode(),
                item.getProduct().getProductName(),
                item.getProduct().getCategory(),
                item.getQuantity(),
                item.getProduct().getUnit(),
                item.getLocation(),
                item.isLowStock() ? "Low Stock" : "Normal"
            };
            model.addRow(row);
        }
    }//GEN-LAST:event_btnSearchNameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnEditQuantity;
    private javax.swing.JButton btnSearchCode;
    private javax.swing.JButton btnSearchName;
    private javax.swing.JButton btnViewProductDetail;
    private javax.swing.JComboBox<String> cbCategory;
    private javax.swing.JTextField fieldProductCode;
    private javax.swing.JTextField fieldProductName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JRadioButton rbtnLowerStockOnly;
    private javax.swing.JTable tbProduct;
    // End of variables declaration//GEN-END:variables
}
