/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.ShippingRole.DeliveryStaffRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.Shipping.ShippingOperationOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.WorkRequest;
import Business.WorkQueue.ProductShippingRequest;
import Business.WorkQueue.MaterialShippingRequest;
import Business.WorkQueue.WholesalesShippingRequest;
import java.util.Date;
import javax.swing.JPanel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.awt.CardLayout;

/**
 *
 * @author chris
 */
public class DeliveryStaffRoleWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private ShippingOperationOrganization operationOrg;
    private Enterprise shippingEnterprise;
    private EcoSystem system;

    /**
     * Creates new form ShippingManagerWorkAreaJPanel
     */
    public DeliveryStaffRoleWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, ShippingOperationOrganization par, Enterprise enterprise, EcoSystem system) {
        initComponents();

        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.operationOrg = par;
        this.shippingEnterprise = enterprise;
        this.system = system;

        populateTable();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        jScrollPaneDeliveries = new javax.swing.JScrollPane();
        tblDeliveries = new javax.swing.JTable();
        panelButtons = new javax.swing.JPanel();
        btnRefresh = new javax.swing.JButton();
        btnStartDelivery = new javax.swing.JButton();
        btnViewDetails = new javax.swing.JButton();
        btnComplete = new javax.swing.JButton();
        lblFilter = new javax.swing.JLabel();
        cmbFilter = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(0, 153, 255));

        lblTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblTitle.setText("Deliveries:");

        tblDeliveries.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Request", "Type", "Item", "Quantity", "Destination", "Status", "Assigned to "
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPaneDeliveries.setViewportView(tblDeliveries);

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        btnStartDelivery.setText("Start Delivery");
        btnStartDelivery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartDeliveryActionPerformed(evt);
            }
        });

        btnViewDetails.setText("Status Details");
        btnViewDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDetailsActionPerformed(evt);
            }
        });

        btnComplete.setText("Complete Delivery");
        btnComplete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelButtonsLayout = new javax.swing.GroupLayout(panelButtons);
        panelButtons.setLayout(panelButtonsLayout);
        panelButtonsLayout.setHorizontalGroup(
            panelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelButtonsLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(btnRefresh)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnStartDelivery)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnViewDetails)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnComplete)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelButtonsLayout.setVerticalGroup(
            panelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelButtonsLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(panelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRefresh)
                    .addComponent(btnStartDelivery)
                    .addComponent(btnViewDetails)
                    .addComponent(btnComplete))
                .addGap(15, 15, 15))
        );

        lblFilter.setText("Filter by Status:");

        cmbFilter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "Pending", "In Progress", "Shipped", "Delivered", " ", " " }));
        cmbFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbFilterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPaneDeliveries)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(380, 380, 380)
                                .addComponent(lblTitle))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(101, 101, 101)
                                .addComponent(lblFilter)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cmbFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(175, 175, 175)
                .addComponent(panelButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(349, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFilter)
                    .addComponent(cmbFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPaneDeliveries, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        populateTable();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnStartDeliveryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartDeliveryActionPerformed
        // TODO add your handling code here:
        WorkRequest wr = getSelectedRequest();
        if (wr == null) {
            return;
        }

        String status = wr.getStatus();
        if (!WorkRequest.STATUS_PENDING.equals(status)
                && !WorkRequest.STATUS_IN_PROGRESS.equals(status)
                && !WorkRequest.STATUS_SHIPPED.equals(status)) {

            JOptionPane.showMessageDialog(this,
                    "Request must be Pending, In Progress, or Shipped to start delivery.");
            return;
        }

        if (wr instanceof WholesalesShippingRequest) {
            ((WholesalesShippingRequest) wr).markInTransit();
        }

        wr.setStatus(WorkRequest.STATUS_IN_PROGRESS);

        JOptionPane.showMessageDialog(this, "Delivery started.");
        populateTable();
    }//GEN-LAST:event_btnStartDeliveryActionPerformed

    private void btnViewDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDetailsActionPerformed
        // TODO add your handling code here:
        WorkRequest wr = getSelectedRequest();
        if (wr == null) {
            return;
        }

        ViewDeliveryStatusDetailsJPanel panel
                = new ViewDeliveryStatusDetailsJPanel(
                        userProcessContainer,
                        userAccount,
                        shippingEnterprise,
                        wr
                );

        userProcessContainer.add("DeliveryStatusDetailsJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnViewDetailsActionPerformed

    private void cmbFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbFilterActionPerformed
        // TODO add your handling code here:
        populateTable();
    }//GEN-LAST:event_cmbFilterActionPerformed

    private void btnCompleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompleteActionPerformed
        // TODO add your handling code here:
        WorkRequest wr = getSelectedRequest();
        if (wr == null) {
            return;
        }

        String status = wr.getStatus();
        if (!WorkRequest.STATUS_IN_PROGRESS.equals(status)
                && !WorkRequest.STATUS_SHIPPED.equals(status)) {
            JOptionPane.showMessageDialog(this,
                    "You can only complete deliveries that are In Progress or Shipped.");
            return;
        }

        wr.setStatus(WorkRequest.STATUS_DELIVERED);
        wr.setResolveDate(new Date());

        if (wr instanceof WholesalesShippingRequest) {
            ((WholesalesShippingRequest) wr).markDelivered();
        }

        JOptionPane.showMessageDialog(this, "Delivery marked as completed.");

        populateTable();
    }//GEN-LAST:event_btnCompleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComplete;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnStartDelivery;
    private javax.swing.JButton btnViewDetails;
    private javax.swing.JComboBox<String> cmbFilter;
    private javax.swing.JScrollPane jScrollPaneDeliveries;
    private javax.swing.JLabel lblFilter;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel panelButtons;
    private javax.swing.JTable tblDeliveries;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) tblDeliveries.getModel();
        model.setRowCount(0);

        String filter = "All";
        if (cmbFilter != null && cmbFilter.getSelectedItem() != null) {
            filter = cmbFilter.getSelectedItem().toString();
        }

        for (WorkRequest wr : operationOrg.getWorkQueue().getWorkRequestList()) {
            if (wr instanceof ProductShippingRequest
                    || wr instanceof MaterialShippingRequest
                    || wr instanceof WholesalesShippingRequest) {

                Object[] row = new Object[7];
                row[0] = wr;

                String statusForRow;

                if (wr instanceof ProductShippingRequest) {
                    ProductShippingRequest psr = (ProductShippingRequest) wr;
                    row[1] = "Product";
                    row[2] = psr.getProductName();
                    row[3] = psr.getQuantity() + " " + psr.getUnit();
                    row[4] = psr.getDestinationStoreName();
                    statusForRow = psr.getStatus();
                    row[6] = psr.getReceiver() == null
                            ? "Unassigned"
                            : psr.getReceiver().getUsername();

                } else if (wr instanceof MaterialShippingRequest) {
                    MaterialShippingRequest msr = (MaterialShippingRequest) wr;
                    row[1] = "Material";
                    row[2] = msr.getMaterialName();
                    row[3] = msr.getQuantity() + " " + msr.getUnit();
                    row[4] = (msr.getTargetEnterprise() == null)
                            ? "-"
                            : msr.getTargetEnterprise().getName();
                    statusForRow = msr.getStatus();
                    row[6] = msr.getReceiver() == null
                            ? "Unassigned"
                            : msr.getReceiver().getUsername();

                } else {
                    WholesalesShippingRequest wsr = (WholesalesShippingRequest) wr;
                    row[1] = "Wholesale";
                    row[2] = wsr.getProductName();
                    row[3] = wsr.getQuantity() + " " + wsr.getUnit();
                    row[4] = wsr.getDestinationAddress();
                    statusForRow = wsr.getShippingStatus();
                    row[6] = wsr.getReceiver() == null
                            ? "Unassigned"
                            : wsr.getReceiver().getUsername();
                }

                if (!"All".equals(filter)) {
                    if (statusForRow == null || !statusForRow.equals(filter)) {
                        continue;
                    }
                }

                row[5] = statusForRow;
                model.addRow(row);
            }
        }
    }

    private WorkRequest getSelectedRequest() {
        int selectedRow = tblDeliveries.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a row.");
            return null;
        }
        return (WorkRequest) tblDeliveries.getValueAt(selectedRow, 0);
    }

}
