/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.ShippingRole.DeliveryStaffRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.Shipping.ShippingOperationOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.WorkRequest;
import Business.WorkQueue.ProductShippingRequest;
import Business.WorkQueue.MaterialShippingRequest;
import Business.WorkQueue.WholesalesShippingRequest;
import Business.WorkQueue.DeliveryConfirmationRequest;
import Business.WorkQueue.MaterialDeliveryConfirmationRequest;
import java.util.Date;
import javax.swing.JPanel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author chris
 */
public class DeliveryStaffRoleWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private ShippingOperationOrganization operationOrg;
    private Enterprise shippingEnterprise;
    private EcoSystem system;

    /**
     * Creates new form ShippingManagerWorkAreaJPanel
     */
    public DeliveryStaffRoleWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, ShippingOperationOrganization par, Enterprise enterprise, EcoSystem system) {
        initComponents();

        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.operationOrg = par;
        this.shippingEnterprise = enterprise;
        this.system = system;

        populateTable();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        jScrollPaneDeliveries = new javax.swing.JScrollPane();
        tblDeliveries = new javax.swing.JTable();
        panelButtons = new javax.swing.JPanel();
        btnRefresh = new javax.swing.JButton();
        btnAssign = new javax.swing.JButton();
        btnStartDelivery = new javax.swing.JButton();
        btnMarkDelivered = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 255));

        lblTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblTitle.setText("Delivery Staff ");

        tblDeliveries.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Request", "Type", "Item", "Quantity", "Destination", "Status", "Assigned to "
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPaneDeliveries.setViewportView(tblDeliveries);

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        btnAssign.setText("Assign to Me");
        btnAssign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignActionPerformed(evt);
            }
        });

        btnStartDelivery.setText("Start Delivery");
        btnStartDelivery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartDeliveryActionPerformed(evt);
            }
        });

        btnMarkDelivered.setText("Mark Delivered and Confirm");
        btnMarkDelivered.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMarkDeliveredActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelButtonsLayout = new javax.swing.GroupLayout(panelButtons);
        panelButtons.setLayout(panelButtonsLayout);
        panelButtonsLayout.setHorizontalGroup(
            panelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnRefresh)
                .addGap(35, 35, 35)
                .addComponent(btnAssign)
                .addGap(27, 27, 27)
                .addComponent(btnStartDelivery)
                .addGap(18, 18, 18)
                .addComponent(btnMarkDelivered)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelButtonsLayout.setVerticalGroup(
            panelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelButtonsLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(panelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRefresh)
                    .addComponent(btnAssign)
                    .addComponent(btnStartDelivery)
                    .addComponent(btnMarkDelivered))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPaneDeliveries, javax.swing.GroupLayout.PREFERRED_SIZE, 729, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 21, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(panelButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(280, 280, 280)
                        .addComponent(lblTitle)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPaneDeliveries, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        populateTable();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnAssignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignActionPerformed
        // TODO add your handling code here:
        WorkRequest wr = getSelectedRequest();
        if (wr == null) {
            return;
        }

        wr.setReceiver(userAccount);
        wr.setStatus(WorkRequest.STATUS_IN_PROGRESS);

        if (!userAccount.getWorkQueue().getWorkRequestList().contains(wr)) {
            userAccount.getWorkQueue().addWorkRequest(wr);
        }

        populateTable();
    }//GEN-LAST:event_btnAssignActionPerformed

    private void btnStartDeliveryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartDeliveryActionPerformed
        // TODO add your handling code here:
        WorkRequest wr = getSelectedRequest();
        if (wr == null) {
            return;
        }

        String status = wr.getStatus();
        if (!WorkRequest.STATUS_PENDING.equals(status)
                && !WorkRequest.STATUS_IN_PROGRESS.equals(status)
                && !WorkRequest.STATUS_SHIPPED.equals(status)) {

            JOptionPane.showMessageDialog(this,
                    "Request must be Pending, In Progress, or Shipped to start delivery.");
            return;
        }

        if (wr instanceof WholesalesShippingRequest) {
            ((WholesalesShippingRequest) wr).markInTransit();
        }

        wr.setStatus(WorkRequest.STATUS_IN_PROGRESS);

        JOptionPane.showMessageDialog(this, "Delivery started.");
        populateTable();
    }//GEN-LAST:event_btnStartDeliveryActionPerformed

    private void btnMarkDeliveredActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMarkDeliveredActionPerformed
        // TODO add your handling code here:
        WorkRequest wr = getSelectedRequest();
        if (wr == null) {
            return;
        }

        wr.setStatus(WorkRequest.STATUS_DELIVERED);
        wr.setResolveDate(new Date());

        if (wr instanceof ProductShippingRequest) {
            ProductShippingRequest psr = (ProductShippingRequest) wr;

            DeliveryConfirmationRequest dcr = new DeliveryConfirmationRequest(psr);
            dcr.setSender(userAccount);
            dcr.setSourceEnterprise(shippingEnterprise);
            dcr.setTargetEnterprise(psr.getTargetEnterprise());
            dcr.setStatus(WorkRequest.STATUS_AWAITING_CONFIRMATION);

            if (psr.getTargetOrganization() != null) {
                dcr.setTargetOrganization(psr.getTargetOrganization());
                psr.getTargetOrganization().getWorkQueue().addWorkRequest(dcr);
            }

        } else if (wr instanceof MaterialShippingRequest) {
            MaterialShippingRequest msr = (MaterialShippingRequest) wr;

            MaterialDeliveryConfirmationRequest mdcr = new MaterialDeliveryConfirmationRequest(msr);
            mdcr.setSender(userAccount);
            mdcr.setSourceEnterprise(shippingEnterprise);
            mdcr.setTargetEnterprise(msr.getTargetEnterprise());
            mdcr.setStatus(WorkRequest.STATUS_AWAITING_CONFIRMATION);

            if (msr.getTargetOrganization() != null) {
                mdcr.setTargetOrganization(msr.getTargetOrganization());
                msr.getTargetOrganization().getWorkQueue().addWorkRequest(mdcr);
            }

        } else if (wr instanceof WholesalesShippingRequest) {
            ((WholesalesShippingRequest) wr).markDelivered();
        }

        JOptionPane.showMessageDialog(this,
                "Marked delivered and created confirmation request (if applicable).");
        populateTable();
    }//GEN-LAST:event_btnMarkDeliveredActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssign;
    private javax.swing.JButton btnMarkDelivered;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnStartDelivery;
    private javax.swing.JScrollPane jScrollPaneDeliveries;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel panelButtons;
    private javax.swing.JTable tblDeliveries;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) tblDeliveries.getModel();
        model.setRowCount(0);

        for (WorkRequest wr : operationOrg.getWorkQueue().getWorkRequestList()) {
            if (wr instanceof ProductShippingRequest
                    || wr instanceof MaterialShippingRequest
                    || wr instanceof WholesalesShippingRequest) {

                Object[] row = new Object[7];
                row[0] = wr;

                if (wr instanceof ProductShippingRequest) {
                    ProductShippingRequest psr = (ProductShippingRequest) wr;
                    row[1] = "Product";
                    row[2] = psr.getProductName();
                    row[3] = psr.getQuantity() + " " + psr.getUnit();
                    row[4] = psr.getDestinationStoreName();
                    row[5] = psr.getStatus();
                    row[6] = psr.getReceiver() == null
                            ? "Unassigned"
                            : psr.getReceiver().getUsername();

                } else if (wr instanceof MaterialShippingRequest) {
                    MaterialShippingRequest msr = (MaterialShippingRequest) wr;
                    row[1] = "Material";
                    row[2] = msr.getMaterialName();
                    row[3] = msr.getQuantity() + " " + msr.getUnit();
                    row[4] = (msr.getTargetEnterprise() == null)
                            ? "-"
                            : msr.getTargetEnterprise().getName();
                    row[5] = msr.getStatus();
                    row[6] = msr.getReceiver() == null
                            ? "Unassigned"
                            : msr.getReceiver().getUsername();

                } else if (wr instanceof WholesalesShippingRequest) {
                    WholesalesShippingRequest wsr = (WholesalesShippingRequest) wr;
                    row[1] = "Wholesale";
                    row[2] = wsr.getProductName();
                    row[3] = wsr.getQuantity() + " " + wsr.getUnit();
                    row[4] = wsr.getDestinationAddress();
                    row[5] = wsr.getShippingStatus();
                    row[6] = wsr.getReceiver() == null
                            ? "Unassigned"
                            : wsr.getReceiver().getUsername();
                }

                model.addRow(row);
            }
        }
    }

    private WorkRequest getSelectedRequest() {
        int selectedRow = tblDeliveries.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a row.");
            return null;
        }
        return (WorkRequest) tblDeliveries.getValueAt(selectedRow, 0);
    }

}
