/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.ShippingRole.DeliveryStaffRole;

import Business.WorkQueue.WorkRequest;
import Business.WorkQueue.ProductShippingRequest;
import Business.WorkQueue.MaterialShippingRequest;
import Business.WorkQueue.WholesalesShippingRequest;
import java.awt.CardLayout;
import javax.swing.JPanel;
import Business.UserAccount.UserAccount;
import Business.Enterprise.Enterprise;

/**
 *
 * @author noora.
 */
public class ViewDeliveryStatusDetailsJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private WorkRequest request;
    private UserAccount userAccount;
    private Enterprise shippingEnterprise;

    /**
     * Creates new form ViewShippingDetailsJPanel
     */
    public ViewDeliveryStatusDetailsJPanel(JPanel userProcessContainer, UserAccount userAccount, Enterprise shippingEnterprise, WorkRequest request) {
        initComponents();

        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.shippingEnterprise = shippingEnterprise;
        this.request = request;

        populateDetails();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        btnBack = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        lblRequestId = new javax.swing.JLabel();
        txtRequestId = new javax.swing.JTextField();
        lblItem = new javax.swing.JLabel();
        lblFrom = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        lblTo = new javax.swing.JLabel();
        txtItem = new javax.swing.JTextField();
        txtFrom = new javax.swing.JTextField();
        txtTo = new javax.swing.JTextField();
        txtStatus = new javax.swing.JTextField();
        lblShippedDate = new javax.swing.JLabel();
        lblDeliveredDate = new javax.swing.JLabel();
        txtDeliveredDate = new javax.swing.JTextField();
        txtShippedDate = new javax.swing.JTextField();

        jCheckBox1.setText("jCheckBox1");

        setBackground(new java.awt.Color(0, 153, 255));

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblTitle.setText("Delivery Status Details");

        lblRequestId.setText("Request ID:");

        txtRequestId.setEditable(false);

        lblItem.setText("Item:");

        lblFrom.setText("From:");

        lblStatus.setText("Status:");

        lblTo.setText("To:");

        txtItem.setEditable(false);

        txtFrom.setEditable(false);

        txtTo.setEditable(false);

        txtStatus.setEditable(false);

        lblShippedDate.setText("Shipped Date:");

        lblDeliveredDate.setText("Delivered Date:");

        txtDeliveredDate.setEditable(false);

        txtShippedDate.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblStatus)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblFrom)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(21, 21, 21)
                                .addComponent(lblTo))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtTo, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(lblRequestId)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtRequestId, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(lblItem)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtItem, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(lblTitle))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblShippedDate)
                                    .addComponent(lblDeliveredDate))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtShippedDate, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addComponent(txtDeliveredDate, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBack)))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblTitle)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStatus))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRequestId)
                    .addComponent(txtRequestId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblItem))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFrom)
                    .addComponent(txtFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblShippedDate)
                    .addComponent(txtShippedDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDeliveredDate)
                    .addComponent(txtDeliveredDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addGap(23, 23, 23))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void populateDetails() {
        txtRequestId.setText(String.valueOf(request.getRequestId()));

        String item = "-";
        String from = "-";
        String to = "-";
        String status = request.getStatus();

        if (request instanceof ProductShippingRequest) {
            ProductShippingRequest psr = (ProductShippingRequest) request;

            item = psr.getProductName();
            from = (psr.getSourceEnterprise() == null)
                    ? "-"
                    : psr.getSourceEnterprise().getName();
            to = psr.getDestinationStoreName();

        } else if (request instanceof MaterialShippingRequest) {
            MaterialShippingRequest msr = (MaterialShippingRequest) request;

            item = msr.getMaterialName();
            from = (msr.getSourceEnterprise() == null)
                    ? "-"
                    : msr.getSourceEnterprise().getName();
            to = (msr.getTargetEnterprise() == null)
                    ? "-"
                    : msr.getTargetEnterprise().getName();

        } else if (request instanceof WholesalesShippingRequest) {
            WholesalesShippingRequest wsr = (WholesalesShippingRequest) request;

            item = wsr.getProductName();
            from = wsr.getOriginAddress();
            to = wsr.getDestinationAddress();
        }

        txtItem.setText(item);
        txtFrom.setText(from);
        txtTo.setText(to);
        txtStatus.setText(status);

        String shippedDateText = (request.getRequestDate() == null)
                ? "-"
                : request.getRequestDate().toString();

        String deliveredDateText = (request.getResolveDate() == null)
                ? "-"
                : request.getResolveDate().toString();

        txtShippedDate.setText(shippedDateText);
        txtDeliveredDate.setText(deliveredDateText);

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel lblDeliveredDate;
    private javax.swing.JLabel lblFrom;
    private javax.swing.JLabel lblItem;
    private javax.swing.JLabel lblRequestId;
    private javax.swing.JLabel lblShippedDate;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTo;
    private javax.swing.JTextField txtDeliveredDate;
    private javax.swing.JTextField txtFrom;
    private javax.swing.JTextField txtItem;
    private javax.swing.JTextField txtRequestId;
    private javax.swing.JTextField txtShippedDate;
    private javax.swing.JTextField txtStatus;
    private javax.swing.JTextField txtTo;
    // End of variables declaration//GEN-END:variables
}
