/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.ManufacturerRole.InventoryManagerRole;

/**
 *
 * @author zhaojinkun
 */
public class RawMaterialInventoryJPanel extends javax.swing.JPanel {

    /**
     * Creates new form RawMaterialInventoryJPanel
     */
    public RawMaterialInventoryJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ProductsTable = new javax.swing.JTable();
        btnOverPerforming = new javax.swing.JButton();
        btnUnderperforming = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel1.setText("Raw Material Inventory Management");

        jLabel2.setText("Search by Name:");

        jButton1.setText("Search");

        ProductsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Material Name ", "Quantity", "Unit", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(ProductsTable);

        btnOverPerforming.setText("Edit Quantity");
        btnOverPerforming.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOverPerformingActionPerformed(evt);
            }
        });

        btnUnderperforming.setText("Add Material");
        btnUnderperforming.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnderperformingActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(203, 203, 203))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 738, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnUnderperforming)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnOverPerforming)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUnderperforming)
                    .addComponent(btnOverPerforming))
                .addContainerGap(82, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnOverPerformingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOverPerformingActionPerformed
        // TODO add your handling code here:
////        DefaultTableModel model = (DefaultTableModel) ProductsTable.getModel();
////        model.setRowCount(0);
////
////        String supplierName = (String) SuppliersComboBox.getSelectedItem();
////        if (supplierName == null) return;
////
////        Supplier selectedSupplier = business.getSupplierDirectory().findSupplier(supplierName);
////        if (selectedSupplier == null) return;
////
////        ProductCatalog pc = selectedSupplier.getProductCatalog();
////
////        for (Product p : pc.getProductList()) {
////            if (p.getOrderPricePerformance() <= 0){
////                continue;
////            }
////            Object[] row = new Object[7];
////            row[0] = p.toString();
////            row[1] = "$" + p.getTargetPrice();
////            row[2] = p.getNumberOfProductSalesAtTarget();
////            row[3] = p.getNumberOfProductSalesAboveTarget();
////            row[4] = p.getNumberOfProductSalesBelowTarget();
////            row[5] = "$" + p.getSalesVolume();
////            row[6] = "$" + p.getOrderPricePerformance();
////            model.addRow(row);
////        }
    }//GEN-LAST:event_btnOverPerformingActionPerformed

    private void btnUnderperformingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnderperformingActionPerformed
        // TODO add your handling code here:
//        DefaultTableModel model = (DefaultTableModel) ProductsTable.getModel();
//        model.setRowCount(0);
//
//        String supplierName = (String) SuppliersComboBox.getSelectedItem();
//        if (supplierName == null) return;
//
//        Supplier selectedSupplier = business.getSupplierDirectory().findSupplier(supplierName);
//        if (selectedSupplier == null) return;
//
//        ProductCatalog pc = selectedSupplier.getProductCatalog();
//
//        for (Product p : pc.getProductList()) {
//            if (p.getOrderPricePerformance() >= 0){
//                continue;
//            }
//            Object[] row = new Object[7];
//            row[0] = p.toString();
//            row[1] = "$" + p.getTargetPrice();
//            row[2] = p.getNumberOfProductSalesAtTarget();
//            row[3] = p.getNumberOfProductSalesAboveTarget();
//            row[4] = p.getNumberOfProductSalesBelowTarget();
//            row[5] = "$" + p.getSalesVolume();
//            row[6] = "$" + p.getOrderPricePerformance();
//            model.addRow(row);
//        }

    }//GEN-LAST:event_btnUnderperformingActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable ProductsTable;
    private javax.swing.JButton btnOverPerforming;
    private javax.swing.JButton btnUnderperforming;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
