/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.ManufacturerRole.InventoryManagerRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.ManufacturerEnterprise;
import Business.Inventory.InventoryItem;
import Business.Material.Material;
import Business.Material.MaterialCatalog;
import Business.Organization.Manufacturer.InventoryOrganization;
import Business.Organization.Organization;
import Business.WorkQueue.RawMaterialRestockRequest;
import java.util.HashSet;
import java.util.Set;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author zhaojinkun
 */
public class RawMaterialInventoryJPanel extends javax.swing.JPanel {

    /**
     * Creates new form RawMaterialInventoryJPanel
     */
    
    JPanel userProcessContainer;
    InventoryOrganization inventoryOrganization;
    Enterprise enterprise;
    EcoSystem system;
    
    public RawMaterialInventoryJPanel(JPanel userProcessContainer, InventoryOrganization inventoryOrganization, Enterprise enterprise, EcoSystem system) {
        this.userProcessContainer = userProcessContainer;
        this.inventoryOrganization = inventoryOrganization;
        this.enterprise = enterprise;
        initComponents();
        populateComboBox();
        populateTable("All");
    }
    
    private void populateComboBox(){
        // Order Status
        cbCategory.removeAllItems();
        cbCategory.addItem("All");
        ManufacturerEnterprise mfg = (ManufacturerEnterprise) enterprise;
        MaterialCatalog materialCatalog = mfg.getMaterialCatalog();

        Set<String> categorySet = new HashSet<>();

        for (Material m : materialCatalog.getMaterialList()) {
            if (m.getCategory() != null && !m.getCategory().isEmpty()) {
                categorySet.add(m.getCategory());
            }
        }

        for (String category : categorySet) {
            cbCategory.addItem(category);
        }
    }
    
    
    
    private void populateTable(String selectedCategory) {
        if (selectedCategory == null) {
            return; 
        }

        DefaultTableModel model = (DefaultTableModel) tbMaterial.getModel();
        model.setRowCount(0);

        boolean showLowStockOnly = rbtnLowerStockOnly.isSelected();   // ⭐ 获取 RadioButton 状态

        for (InventoryItem item : enterprise.getInventory().getMaterialInventory()) {
            String itemCategory = item.getMaterial().getCategory();


            if (!selectedCategory.equals("All")
                    && !itemCategory.equalsIgnoreCase(selectedCategory)) {
                continue;
            }

            if (showLowStockOnly && !item.isLowStock()) {
                continue; 
            }

            Object[] row = new Object[]{
                item.getMaterial().getMaterialCode(),
                item.getMaterial().getMaterialName(),
                item.getMaterial().getCategory(),
                item.getQuantity(),
                item.getMaterial().getUnit(),
                item.getLocation(),
                item.isLowStock() ? "Low Stock" : "Normal"
            };

            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fieldMaterialCode = new javax.swing.JTextField();
        btnSearchCode = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbMaterial = new javax.swing.JTable();
        btnEditQuantity = new javax.swing.JButton();
        btnRestorckRequest = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        cbCategory = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        btnViewMaterialDetail = new javax.swing.JButton();
        rbtnLowerStockOnly = new javax.swing.JRadioButton();
        btnBack = new javax.swing.JButton();
        btnSearchName = new javax.swing.JButton();
        fieldMaterialName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        jTextField2.setText("jTextField2");

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel1.setText("Raw Material Inventory Management");

        jLabel2.setText("Material Code:");

        btnSearchCode.setText("Search");
        btnSearchCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchCodeActionPerformed(evt);
            }
        });

        tbMaterial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Material Code ", "Material Name", "Category", "Qty", "Unit", "Location", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbMaterial);

        btnEditQuantity.setText("Edit Quantity");
        btnEditQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditQuantityActionPerformed(evt);
            }
        });

        btnRestorckRequest.setText("Create Restock Request");
        btnRestorckRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestorckRequestActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 2, 14)); // NOI18N
        jLabel3.setText("Filters:");

        cbCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCategoryActionPerformed(evt);
            }
        });

        jLabel4.setText("Category:");

        btnViewMaterialDetail.setText("View Material Details");
        btnViewMaterialDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewMaterialDetailActionPerformed(evt);
            }
        });

        rbtnLowerStockOnly.setText("Low Stock Only");
        rbtnLowerStockOnly.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnLowerStockOnlyActionPerformed(evt);
            }
        });

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnSearchName.setText("Search");
        btnSearchName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchNameActionPerformed(evt);
            }
        });

        jLabel5.setText("Material Name:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2)
                    .addComponent(jSeparator1)
                    .addComponent(jSeparator3)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnViewMaterialDetail)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnEditQuantity)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnRestorckRequest))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(fieldMaterialCode, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(cbCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnSearchCode, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(rbtnLowerStockOnly)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(fieldMaterialName, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnSearchName, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(90, 90, 90)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(216, 216, 216)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 176, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBack))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(cbCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rbtnLowerStockOnly))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(fieldMaterialCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchCode))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(fieldMaterialName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchName))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnViewMaterialDetail)
                    .addComponent(btnEditQuantity)
                    .addComponent(btnRestorckRequest))
                .addContainerGap(13, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditQuantityActionPerformed
        // TODO add your handling code here:
        int selectedRow = tbMaterial.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a material to edit.", "No Selection", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String materialCode = (String) tbMaterial.getValueAt(selectedRow, 0);

        InventoryItem item = enterprise.getInventory().findByMaterialCode(materialCode);

        String newQtyStr = JOptionPane.showInputDialog(this, "Enter new quantity for " + item.getMaterial().getMaterialName() + ":", item.getQuantity());
        if (newQtyStr == null) {
            return;
        }

        try {
            int newQty = Integer.parseInt(newQtyStr);
            if (newQty < 0) {
                JOptionPane.showMessageDialog(this, "Quantity cannot be negative.", "Invalid Input", JOptionPane.WARNING_MESSAGE);
                return;
            }
            
            if (newQty > item.getMaxStockLevel()) {
                JOptionPane.showMessageDialog(this, 
                    "Quantity cannot exceed max stock level (" + item.getMaxStockLevel() + ").", 
                    "Invalid Input", 
                    JOptionPane.WARNING_MESSAGE);
                return;
            }

            item.setQuantity(newQty);

            String selectedCategory = (String) cbCategory.getSelectedItem();
            populateTable(selectedCategory);

            JOptionPane.showMessageDialog(this, "Quantity updated successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Please enter a valid integer.", "Invalid Input", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnEditQuantityActionPerformed

    private void btnRestorckRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestorckRequestActionPerformed
        int selectedRow = tbMaterial.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a material to request restock.", "No Selection", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String materialCode = (String) tbMaterial.getValueAt(selectedRow, 0);
        InventoryItem item = enterprise.getInventory().findByMaterialCode(materialCode);
        if (item == null) {
            JOptionPane.showMessageDialog(this, "Selected material not found in inventory.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Material material = item.getMaterial();


        String quantityStr = JOptionPane.showInputDialog(this, "Enter quantity to restock:", "Restock Quantity", JOptionPane.PLAIN_MESSAGE);
        if (quantityStr == null) return; 
        int quantity;
        try {
            quantity = Integer.parseInt(quantityStr);
            if (quantity <= 0) throw new NumberFormatException();
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid quantity.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String[] urgencies = {"Normal", "Urgent", "Critical"};
        String urgency = (String) JOptionPane.showInputDialog(this, "Select urgency level:", 
                                    "Urgency", JOptionPane.PLAIN_MESSAGE, null, urgencies, "Normal");
        if (urgency == null) urgency = "Normal";


        RawMaterialRestockRequest request = new RawMaterialRestockRequest(material, quantity);
        request.setUrgencyLevel(urgency);

 
        Organization rmProcurementOrg = null;
        for (Organization org : enterprise.getOrganizationDirectory().getOrganizationList()) {
            rmProcurementOrg = org;
            break;
        }

        if (rmProcurementOrg != null) {
            rmProcurementOrg.getWorkQueue().addWorkRequest(request);
            JOptionPane.showMessageDialog(this, "Restock request submitted:\n" + request.toString(), "Success", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "No RM Procurement Organization found to handle this request.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnRestorckRequestActionPerformed

    private void btnViewMaterialDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewMaterialDetailActionPerformed
        // TODO add your handling code here:
        int selectedRow = tbMaterial.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a material first.", "No Selection", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String materialCode = (String) tbMaterial.getValueAt(selectedRow, 0);
        InventoryItem item = enterprise.getInventory().findByMaterialCode(materialCode);

        if (item != null) {
            Material mat = item.getMaterial();
            String details = "Material Code: " + mat.getMaterialCode() + "\n"
                           + "Material Name: " + mat.getMaterialName() + "\n"
                           + "Category: " + mat.getCategory() + "\n"
                           + "Description: " + mat.getDescription() + "\n"
                           + "Quantity: " + item.getQuantity() + "\n"
                           + "Unit: " + mat.getUnit() + "\n"
                           + "Location: " + item.getLocation() + "\n"
                           + "Min Stock Level: " + item.getMinStockLevel() + "\n"
                           + "Max Stock Level: " + item.getMaxStockLevel() + "\n"
                           + "Status: " + (item.isLowStock() ? "Low Stock" : "Normal");

            JOptionPane.showMessageDialog(this, details, "Material Details", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Material not found in inventory.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnViewMaterialDetailActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
         userProcessContainer.remove(this);
        ((java.awt.CardLayout) userProcessContainer.getLayout()).next(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void cbCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCategoryActionPerformed
        // TODO add your handling code here:
        String selectedCategory = (String) cbCategory.getSelectedItem();
        populateTable(selectedCategory);
    }//GEN-LAST:event_cbCategoryActionPerformed

    private void rbtnLowerStockOnlyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnLowerStockOnlyActionPerformed
        // TODO add your handling code here:
        String selectedCategory = (String) cbCategory.getSelectedItem();
        populateTable(selectedCategory);
        
    }//GEN-LAST:event_rbtnLowerStockOnlyActionPerformed

    private void btnSearchCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchCodeActionPerformed
        // TODO add your handling code here:
         String materialCode = fieldMaterialCode.getText().trim();
    
        DefaultTableModel model = (DefaultTableModel) tbMaterial.getModel();
        model.setRowCount(0); 

        if (materialCode.isEmpty()) {
            populateTable("All"); 
            return;
        }

        InventoryItem item = enterprise.getInventory().findByMaterialCode(materialCode);

        if (item != null) {
            if (rbtnLowerStockOnly.isSelected() && !item.isLowStock()) {
                return; 
            }

            Object[] row = new Object[]{
                item.getMaterial().getMaterialCode(),
                item.getMaterial().getMaterialName(),
                item.getMaterial().getCategory(),
                item.getQuantity(),
                item.getMaterial().getUnit(),
                item.getLocation(),
                item.isLowStock() ? "Low Stock" : "Normal"
            };
            model.addRow(row);
        } else {
            JOptionPane.showMessageDialog(this, "No material found with code: " + materialCode);
        }
        String selectedCategory = (String) cbCategory.getSelectedItem();
        populateTable(selectedCategory);

    }//GEN-LAST:event_btnSearchCodeActionPerformed

    private void btnSearchNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchNameActionPerformed
        // TODO add your handling code here:
         String searchName = fieldMaterialName.getText().trim().toLowerCase();
    
        DefaultTableModel model = (DefaultTableModel) tbMaterial.getModel();
        model.setRowCount(0);

        if (searchName.isEmpty()) {
            populateTable("All");
            return;
        }

        for (InventoryItem item : enterprise.getInventory().getMaterialInventory()) {
            String materialName = item.getMaterial().getMaterialName().toLowerCase();

            if (!materialName.contains(searchName)) {
                continue; 
            }

            if (rbtnLowerStockOnly.isSelected() && !item.isLowStock()) {
                continue;
            }

            Object[] row = new Object[]{
                item.getMaterial().getMaterialCode(),
                item.getMaterial().getMaterialName(),
                item.getMaterial().getCategory(),
                item.getQuantity(),
                item.getMaterial().getUnit(),
                item.getLocation(),
                item.isLowStock() ? "Low Stock" : "Normal"
            };
            model.addRow(row);
        }
    }//GEN-LAST:event_btnSearchNameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnEditQuantity;
    private javax.swing.JButton btnRestorckRequest;
    private javax.swing.JButton btnSearchCode;
    private javax.swing.JButton btnSearchName;
    private javax.swing.JButton btnViewMaterialDetail;
    private javax.swing.JComboBox<String> cbCategory;
    private javax.swing.JTextField fieldMaterialCode;
    private javax.swing.JTextField fieldMaterialName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JRadioButton rbtnLowerStockOnly;
    private javax.swing.JTable tbMaterial;
    // End of variables declaration//GEN-END:variables
}
