/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.RMSupplierRole.RMInventoryManagerRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.RawMaterialSupplier.RMInventoryOrganization;
import Business.UserAccount.UserAccount;
import Business.Material.Material;
import javax.swing.JPanel;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author chris
 */
public class RMInventoryManagerWorkAreaJPanel extends javax.swing.JPanel {
    
    private JPanel userProcessContainer;
    private UserAccount account;
    private RMInventoryOrganization organization;
    private Enterprise enterprise;
    private EcoSystem system;
    
    private Material selectedMaterial;

    /**
     * Creates new form RMInventoryManagerWorkAreaJPanel
     */
    public RMInventoryManagerWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, RMInventoryOrganization rmInventoryOrganization, Enterprise enterprise, EcoSystem system) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.organization = rmInventoryOrganization;
        this.enterprise = enterprise;
        this.system = system;
        
        populateTable();
    }
    
    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) tblInventory.getModel();
    model.setRowCount(0);

    if (organization == null) {
        System.out.println("populateTable: organization is null");
        return;
    }

    System.out.println("populateTable: inventory size = " + organization.getInventoryList().size());

    for (Material m : organization.getInventoryList()) {
        Object[] row = new Object[4];
        row[0] = m.getMaterialCode();
        row[1] = m.getMaterialName();
        row[2] = m.getQuantity();
        row[3] = m.getUnit();
        model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblInventory = new javax.swing.JTable();
        lblMaterialName = new javax.swing.JLabel();
        txtMaterialName = new javax.swing.JTextField();
        lblQuantity = new javax.swing.JLabel();
        txtQuantity = new javax.swing.JTextField();
        lblUnit = new javax.swing.JLabel();
        txtUnits = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();

        jLabel1.setText("Raw Material Inventory Manager Role");

        btnBack.setText("<<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel2.setText("Current Inventory");

        tblInventory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Code", "Material", "Quantity", "Unit"
            }
        ));
        jScrollPane1.setViewportView(tblInventory);

        lblMaterialName.setText("Material Name:");

        lblQuantity.setText("Quantity:");

        lblUnit.setText("Unit:");

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(313, 313, 313)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnSave)
                                    .addComponent(btnAdd))
                                .addGap(146, 146, 146)
                                .addComponent(btnEdit))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblMaterialName)
                                    .addComponent(lblQuantity))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtMaterialName, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(82, 82, 82)
                                        .addComponent(lblUnit)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtUnits, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnBack))
                                .addComponent(btnRefresh)))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 774, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBack))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMaterialName)
                    .addComponent(txtMaterialName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUnit)
                    .addComponent(txtUnits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblQuantity)
                            .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                        .addComponent(btnAdd)
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnRefresh)
                            .addComponent(btnSave))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnEdit))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        populateTable();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        String name = txtMaterialName.getText().trim();
    String unit = txtUnits.getText().trim();
    String qtyStr = txtQuantity.getText().trim();

    if (name.isEmpty() || unit.isEmpty() || qtyStr.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please enter material name, quantity, and unit.");
        return;
    }

    int qty;
    try {
        qty = Integer.parseInt(qtyStr);
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Quantity must be a whole number.");
        return;
    }

    if (qty <= 0) {
        JOptionPane.showMessageDialog(this, "Quantity must be greater than zero.");
        return;
    }


    Material existing = organization.findMaterialByName(name);
    Material newMat = null;

    if (existing == null) {
        String code = "RM-" + (organization.getInventoryList().size() + 1);
        newMat = new Material(code, name, 0.0, unit);
        newMat.setQuantity(qty);
        organization.getInventoryList().add(newMat);
        System.out.println("Added NEW material: " + newMat.getMaterialCode() + " / " + newMat.getMaterialName());
    } else {
        existing.setQuantity(existing.getQuantity() + qty);
        if (existing.getUnit() == null || existing.getUnit().isEmpty()) {
            existing.setUnit(unit);
        }
        newMat = existing;
        System.out.println("UPDATED existing material: " + existing.getMaterialCode() + " / " + existing.getMaterialName());
    }

    // ----- directly add/update the table model as well -----
    DefaultTableModel model = (DefaultTableModel) tblInventory.getModel();
    
    // simple approach: repopulate whole table from list
    model.setRowCount(0);
    for (Material m : organization.getInventoryList()) {
        Object[] row = new Object[4];
        row[0] = m.getMaterialCode();
        row[1] = m.getMaterialName();
        row[2] = m.getQuantity();
        row[3] = m.getUnit();
        model.addRow(row);
    }

    System.out.println("Inventory size after add = " + organization.getInventoryList().size());

    JOptionPane.showMessageDialog(this, "Inventory updated.");
    clearFields();                   
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblInventory.getSelectedRow();
    if (selectedRow < 0) {
        JOptionPane.showMessageDialog(this, "Please select a material from the table.");
        return;
    }

    String materialName = (String) tblInventory.getValueAt(selectedRow, 1);
    selectedMaterial = organization.findMaterialByName(materialName);

    if (selectedMaterial == null) {
        JOptionPane.showMessageDialog(this, "Selected material not found in inventory.");
        return;
    }

    txtMaterialName.setText(selectedMaterial.getMaterialName());
    txtUnits.setText(selectedMaterial.getUnit());
    txtQuantity.setText(String.valueOf(selectedMaterial.getQuantity()));
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        if (selectedMaterial == null) {
        JOptionPane.showMessageDialog(this, "Please select a material and click Edit before saving.");
        return;
    }

    String name = txtMaterialName.getText().trim();
    String unit = txtUnits.getText().trim();
    String qtyStr = txtQuantity.getText().trim();

    if (name.isEmpty() || unit.isEmpty() || qtyStr.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please enter material name, quantity, and unit.");
        return;
    }

    int qty;
    try {
        qty = Integer.parseInt(qtyStr);
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Quantity must be a whole number.");
        return;
    }

    if (qty < 0) {
        JOptionPane.showMessageDialog(this, "Quantity cannot be negative.");
        return;
    }

    selectedMaterial.setMaterialName(name);
    selectedMaterial.setUnit(unit);
    selectedMaterial.setQuantity(qty);

    JOptionPane.showMessageDialog(this, "Material updated.");
    selectedMaterial = null;
    clearFields();
    populateTable();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void clearFields() {
        txtMaterialName.setText("");
        txtUnits.setText("");
        txtQuantity.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblMaterialName;
    private javax.swing.JLabel lblQuantity;
    private javax.swing.JLabel lblUnit;
    private javax.swing.JTable tblInventory;
    private javax.swing.JTextField txtMaterialName;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JTextField txtUnits;
    // End of variables declaration//GEN-END:variables

    
}
